version: '3'

services:
    search:
        container_name: search_service
        image: elasticsearch:6.8.8
        environment:
            - cluster.name=docker-cluster
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            -   9200:9200
        volumes:
            -   elasticsearch:/usr/share/elasticsearch/data

    search_server:
        container_name: search_server
        restart: unless-stopped
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            -   9000:9000
        depends_on:
            -   search

    nginx:
        container_name: nginx
        depends_on:
            -   search_server
        image: nginx:mainline-alpine
        restart: always
        ports:
            -   80:80
            -   443:443
        volumes:
        -   ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        -   ./nginx/logs:/etc/nginx/logs

volumes:
    elasticsearch: