version: '3'

services:
    search:
        container_name: search_service
        image: elasticsearch:6.8.8
        environment:
            - cluster.name=docker-cluster
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
volumes:
    elasticsearch: